# Generated by Django 6.0 on 2025-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='feedback_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='readability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aireport',
            name='suggested_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
