# Generated by Django 6.0 on 2025-12-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling_errors', models.JSONField(default=list)),
                ('grammar_errors', models.JSONField(default=list)),
                ('clarity_suggestions', models.JSONField(default=list)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('matched_text', models.TextField(blank=True, null=True)),
                ('readability_score', models.FloatField(default=0.0)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('suggested_grade', models.IntegerField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='core.submission')),
            ],
        ),
        migrations.DeleteModel(
            name='AIReport',
        ),
    ]
