# Generated by Django 6.0 on 2026-01-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aireport_delete_analysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='formatting_analysis',
            field=models.JSONField(default=dict, help_text='AI Analysis of formatting compliance'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='formatting_instructions',
            field=models.TextField(blank=True, help_text='Specific formatting rules (e.g., Font size 12, Times New Roman, Double spacing).', null=True),
        ),
    ]
