# Generated by Django 6.0 on 2026-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aireport_formatting_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='detailed_spelling_errors',
            field=models.JSONField(default=list, help_text='Detailed spelling errors with location and context'),
        ),
    ]
